CREATE TABLE IF NOT EXISTS game_states (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_board TEXT NOT NULL,
  player_one_wins TEXT NOT NULL,
  player_two_wins TEXT NOT NULL,
  -- username TEXT NOT NULL UNIQUE,
  -- password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);